// <auto-generated />
using System;
using GameDB.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameDB.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601121743_AddNormalizedNameToGame")]
    partial class AddNormalizedNameToGame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameDB.Domain.Entities.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlertId"));

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("boolean");

                    b.Property<string>("AutoUpdateMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ReferenceLowest")
                        .HasColumnType("numeric");

                    b.Property<int?>("ShopId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AlertId");

                    b.HasIndex(new[] { "GameId" }, "IX_Alert_GameId");

                    b.HasIndex(new[] { "ShopId" }, "IX_Alert_ShopId");

                    b.HasIndex(new[] { "UserId" }, "IX_Alert_UserId");

                    b.ToTable("Alert", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeveloperId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeveloperId");

                    b.HasIndex(new[] { "Name" }, "IX_Developer_Name")
                        .IsUnique();

                    b.ToTable("Developer", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeveloperId")
                        .HasColumnType("integer");

                    b.Property<string>("HeaderImage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("IconImage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Basic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GameId");

                    b.HasIndex(new[] { "DeveloperId" }, "IX_Game_DeveloperId");

                    b.HasIndex(new[] { "ImportStatus" }, "IX_Game_ImportStatus");

                    b.HasIndex(new[] { "NormalizedName" }, "IX_Game_NormalizedName");

                    b.HasIndex(new[] { "PublisherId" }, "IX_Game_PublisherId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.GameExternalId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("GameShopShopId")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameShopShopId");

                    b.HasIndex(new[] { "GameId", "ShopId" }, "UQ_GameExternalId_GameId_ShopId")
                        .IsUnique();

                    b.HasIndex(new[] { "ShopId", "ExternalId" }, "UQ_GameExternalId_ShopId_ExternalId")
                        .IsUnique();

                    b.ToTable("GameExternalId", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.GameOffer", b =>
                {
                    b.Property<int>("GameOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameOfferId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("CurrentDiscount")
                        .HasColumnType("smallint");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<decimal?>("FinalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("(\"CurrentPrice\" * ((1)::numeric - ((\"CurrentDiscount\")::numeric / 100.0)))", true);

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("ItadUuid")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("GameOfferId");

                    b.HasIndex(new[] { "GameId" }, "IX_GameOffer_GameId");

                    b.HasIndex(new[] { "ShopId" }, "IX_GameOffer_ShopId");

                    b.ToTable("GameOffer", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.GameShop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShopId"));

                    b.Property<string>("ApiBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShopId");

                    b.ToTable("GameShop", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GenreId");

                    b.HasIndex(new[] { "Name" }, "IX_Genre_Name")
                        .IsUnique();

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex(new[] { "UserId" }, "IX_Notification_UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<int>("PriceHistory1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PriceHistory");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceHistory1"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("DiscountPercent")
                        .HasColumnType("smallint");

                    b.Property<int>("GameOfferId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LowestPrice")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("LowestPriceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PriceHistory1");

                    b.HasIndex(new[] { "GameOfferId" }, "IX_PriceHistory_GameOfferId");

                    b.ToTable("PriceHistory", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PublisherId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PublisherId");

                    b.HasIndex(new[] { "Name" }, "IX_Publisher_Name")
                        .IsUnique();

                    b.ToTable("Publisher", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.HasIndex(new[] { "Name" }, "IX_Tag_Name")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("SteamId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ_User_Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex(new[] { "SteamId" }, "UQ_User_SteamId")
                        .IsUnique()
                        .HasFilter("\"SteamId\" IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.UserLibrary", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GameId", "ShopId");

                    b.HasIndex(new[] { "GameId" }, "IX_UserLibrary_GameId");

                    b.HasIndex(new[] { "ShopId" }, "IX_UserLibrary_ShopId");

                    b.ToTable("UserLibrary", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.UserShopProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("ExternalUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId");

                    b.HasIndex(new[] { "ShopId" }, "IX_UserShopProfile_ShopId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserShopProfile_UserId");

                    b.ToTable("UserShopProfile", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Wishlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex(new[] { "GameId" }, "IX_Wishlist_GameId");

                    b.ToTable("Wishlist", (string)null);
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex(new[] { "GenreId" }, "IX_GameGenre_GenreId");

                    b.ToTable("GameGenre", (string)null);
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("GameId", "TagId");

                    b.HasIndex(new[] { "TagId" }, "IX_GameTag_TagId");

                    b.ToTable("GameTag", (string)null);
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Alert", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Game", "Game")
                        .WithMany("Alerts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.GameShop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.HasOne("GameDB.Domain.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Game", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId");

                    b.HasOne("GameDB.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Developer");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.GameExternalId", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Game", "Game")
                        .WithMany("ExternalIds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.GameShop", null)
                        .WithMany("GameExternalIds")
                        .HasForeignKey("GameShopShopId");

                    b.HasOne("GameDB.Domain.Entities.GameShop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.GameOffer", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Game", "Game")
                        .WithMany("GameOffers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.GameShop", "Shop")
                        .WithMany("GameOffers")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Notification", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.GameOffer", "GameOffer")
                        .WithMany("PriceHistories")
                        .HasForeignKey("GameOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PriceHistory_GameOffer_PriceChangeRecordedId");

                    b.Navigation("GameOffer");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.UserLibrary", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Game", "Game")
                        .WithMany("UserLibraries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.GameShop", "Shop")
                        .WithMany("UserLibraries")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.User", "User")
                        .WithMany("UserLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.UserShopProfile", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.GameShop", "Shop")
                        .WithMany("UserShopProfiles")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.User", "User")
                        .WithMany("UserShopProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Wishlist", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Game", "Game")
                        .WithMany("Wishlists")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.HasOne("GameDB.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameDB.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Game", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ExternalIds");

                    b.Navigation("GameOffers");

                    b.Navigation("UserLibraries");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.GameOffer", b =>
                {
                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.GameShop", b =>
                {
                    b.Navigation("GameExternalIds");

                    b.Navigation("GameOffers");

                    b.Navigation("UserLibraries");

                    b.Navigation("UserShopProfiles");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameDB.Domain.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Notifications");

                    b.Navigation("UserLibraries");

                    b.Navigation("UserShopProfiles");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
