GET http://localhost:5295/catalog
###
POST http://localhost:5295/api/admin/import/basic
###
POST http://localhost:5295/api/admin/import/enrich/start
###
POST http://localhost:5295/api/admin/import/enrich/stop
###
POST http://localhost:5295/api/admin/import/prices/start?batchSize=100
###
POST http://localhost:5295/api/admin/import/prices/stop
###
GET http://localhost:5295/api/admin/dashboard
###
GET https://steamspy.com/api.php?request=appdetails&appid=730
###
POST https://id.twitch.tv/oauth2/token?client_id=&client_secret=&grant_type=client_credentials
###
POST https://api.igdb.com/v4/games
Client-ID:
Authorization: Bearer
Content-Type: text/plain

search "Counter-Strike";
fields name, summary, storyline;
limit 1;
###
GET http://localhost:5295/api/bot/users/1/profile

Header: X-Bot-Api-Key: changeme-secret